name: Deploy Laravel App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Build and Deploy Containers
        env:
          TUNNEL_TOKEN: ${{ secrets.TUNNEL_TOKEN }}
        run: |
          docker compose --env-file .env build --no-cache --provenance=false
          docker compose --env-file .env up -d
          sleep 10
          docker compose exec -T app php artisan migrate --force
          docker compose exec -T app php artisan optimize
